'use client'

import { useState } from 'react'
import PDFExport from './PDFExport'

interface NoteEditorProps {
  initialTranscript?: string
  onSaveNote?: (note: string) => void
  userId: string
  selectedClient?: { id: string; name?: string } | null
}

export default function NoteEditor({ 
  initialTranscript = '', 
  onSaveNote,
  userId,
  selectedClient 
}: NoteEditorProps) {
  const [transcript, setTranscript] = useState(initialTranscript)
  const [polishedNote, setPolishedNote] = useState('')
  const [useAbbreviations, setUseAbbreviations] = useState(true)
  const [translate, setTranslate] = useState(false)
  const [serviceType, setServiceType] = useState('Social & Domestic Support')
  const [duration, setDuration] = useState(60)
  const [isProcessing, setIsProcessing] = useState(false)
  const [status, setStatus] = useState('')

  // Simple formatting without AI
  const formatNote = (text: string) => {
    const now = new Date()
    const time = now.toLocaleTimeString('en-AU', { hour: '2-digit', minute: '2-digit' })
    
    // Clean up the transcript
    let cleaned = text
      .replace(/\b(um|uh|er|ah|like|you know)\b/gi, '')
      .replace(/\b(\w+)\s+\1\b/gi, '$1')
      .replace(/\s+/g, ' ')
      .trim()
    cleaned = cleaned.charAt(0).toUpperCase() + cleaned.slice(1)

    const client = selectedClient?.name || '[Client Name]'
    const service = useAbbreviations ? 'S&D' : serviceType
    const activities = useAbbreviations ? 'ACTIVITIES:' : 'ACTIVITIES UNDERTAKEN:'
    const wellbeing = useAbbreviations ? 'WELLBEING:' : 'WELLBEING/OUTCOME:'

    return `Client: ${client}
Date/Time: ${time} – ${time}
Service Type: ${service}

${activities}
${cleaned}

${wellbeing}
- Client remained happy, healthy, and engaged throughout the appointment.
- All tasks completed successfully.
- Client expressed satisfaction with support provided.

DEPARTURE:
Left at ${time} on time.
Client safe, comfortable, and not requiring further assistance.

---
Generated by EziNotes - Review and edit before submitting`
  }

  const handlePolish = () => {
    if (!transcript.trim()) {
      setStatus('Please record or type some text first')
      return
    }

    setIsProcessing(true)
    setStatus('Formatting...')

    // Simple local formatting (no API needed)
    setTimeout(() => {
      const formatted = formatNote(transcript)
      setPolishedNote(formatted)
      setStatus('Formatted!')
      setIsProcessing(false)
    }, 500)
  }

  const handleSave = async () => {
    if (!polishedNote.trim()) {
      setStatus('Format a note first')
      return
    }

    setIsProcessing(true)
    setStatus('Saving...')

    try {
      const response = await fetch('/api/notes', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          userId,
          clientId: selectedClient?.id || null,
          transcript,
          polishedNote: polishedNote,
          serviceType,
          durationMinutes: duration,
        }),
      })

      const data = await response.json()
      
      if (data.note) {
        setStatus('Saved!')
        if (onSaveNote) onSaveNote(polishedNote)
      } else {
        setStatus('Saved locally')
      }
    } catch (err) {
      setStatus('Saved locally')
    }

    setIsProcessing(false)
  }

  const copyToClipboard = () => {
    navigator.clipboard.writeText(polishedNote)
    setStatus('Copied!')
  }

  return (
    <div style={{ padding: '24px' }}>
      {/* Service Type & Duration */}
      <div style={{ display: 'flex', gap: '12px', marginBottom: '16px' }}>
        <select
          value={serviceType}
          onChange={(e) => setServiceType(e.target.value)}
          style={{
            flex: 1,
            padding: '10px',
            borderRadius: '8px',
            border: '1px solid #e5e7eb',
            fontSize: '13px',
            background: 'white',
          }}
        >
          <option>Social & Domestic Support</option>
          <option>Transport</option>
          <option>Community Access</option>
          <option>Therapy Support</option>
          <option>Household Tasks</option>
        </select>
        
        <select
          value={duration}
          onChange={(e) => setDuration(Number(e.target.value))}
          style={{
            width: '100px',
            padding: '10px',
            borderRadius: '8px',
            border: '1px solid #e5e7eb',
            fontSize: '13px',
            background: 'white',
          }}
        >
          <option value={30}>30 min</option>
          <option value={60}>1 hr</option>
          <option value={90}>1.5 hr</option>
          <option value={120}>2 hr</option>
          <option value={180}>3 hr</option>
          <option value={240}>4 hr</option>
        </select>
      </div>

      {/* Settings */}
      <div style={{ 
        display: 'flex', 
        gap: '16px', 
        marginBottom: '16px',
        flexWrap: 'wrap'
      }}>
        <label style={{ display: 'flex', alignItems: 'center', gap: '8px', cursor: 'pointer', fontSize: '13px' }}>
          <input
            type="checkbox"
            checked={useAbbreviations}
            onChange={(e) => setUseAbbreviations(e.target.checked)}
          />
          Abbreviations
        </label>
        
        <label style={{ display: 'flex', alignItems: 'center', gap: '8px', cursor: 'pointer', fontSize: '13px' }}>
          <input
            type="checkbox"
            checked={translate}
            onChange={(e) => setTranslate(e.target.checked)}
          />
          Translate
        </label>
      </div>

      {/* Transcript Input */}
      <div style={{ marginBottom: '16px' }}>
        <textarea
          value={transcript}
          onChange={(e) => setTranscript(e.target.value)}
          placeholder="Your voice transcript will appear here, or type directly..."
          style={{
            width: '100%',
            minHeight: '80px',
            padding: '12px',
            borderRadius: '12px',
            border: '1px solid #e5e7eb',
            fontSize: '14px',
            resize: 'vertical',
            fontFamily: 'inherit',
            boxSizing: 'border-box'
          }}
        />
      </div>

      {/* Action Buttons */}
      <div style={{ display: 'flex', gap: '8px', marginBottom: '16px' }}>
        <button
          onClick={handlePolish}
          disabled={isProcessing || !transcript.trim()}
          style={{
            flex: 1,
            padding: '12px',
            borderRadius: '8px',
            border: 'none',
            background: isProcessing ? '#d1d5db' : '#10b981',
            color: 'white',
            fontSize: '14px',
            fontWeight: '600',
            cursor: isProcessing ? 'not-allowed' : 'pointer',
          }}
        >
          ✨ Polish
        </button>
        
        <button
          onClick={handleSave}
          disabled={isProcessing || !polishedNote}
          style={{
            flex: 1,
            padding: '12px',
            borderRadius: '8px',
            border: 'none',
            background: isProcessing ? '#d1d5db' : '#2563eb',
            color: 'white',
            fontSize: '14px',
            fontWeight: '600',
            cursor: isProcessing ? 'not-allowed' : 'pointer',
          }}
        >
          💾 Save
        </button>
      </div>

      {/* Polished Output */}
      {polishedNote && (
        <div>
          <div style={{ 
            fontSize: '14px', 
            color: '#666', 
            marginBottom: '8px',
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center'
          }}>
            <span>Polished Note</span>
            <div style={{ display: 'flex', gap: '8px' }}>
              <button
                onClick={copyToClipboard}
                style={{
                  padding: '6px 12px',
                  borderRadius: '8px',
                  border: 'none',
                  background: '#f3f4f6',
                  color: '#374151',
                  fontSize: '12px',
                  cursor: 'pointer'
                }}
              >
                📋 Copy
              </button>
              <PDFExport 
                note={polishedNote}
                serviceType={serviceType}
              />
            </div>
          </div>
          <div style={{
            background: '#f3f4f6',
            borderRadius: '12px',
            padding: '16px',
            whiteSpace: 'pre-wrap',
            fontSize: '14px',
            fontFamily: 'monospace',
            maxHeight: '200px',
            overflow: 'auto'
          }}>
            {polishedNote}
          </div>
        </div>
      )}

      {/* Status */}
      {status && (
        <p style={{ 
          textAlign: 'center', 
          marginTop: '12px', 
          fontSize: '13px',
          color: '#10b981'
        }}>
          {status}
        </p>
      )}
    </div>
  )
}
