'use client'

interface PDFExportProps {
  note: string
  clientName?: string
  serviceType?: string
}

export default function PDFExport({ note, clientName = '', serviceType = '' }: PDFExportProps) {
  const generatePDF = () => {
    const content = `
<!DOCTYPE html>
<html>
<head>
  <title>EziNotes - ${clientName || 'NDIS Note'}</title>
  <style>
    body { 
      font-family: Arial, sans-serif; 
      padding: 40px; 
      max-width: 800px; 
      margin: 0 auto;
      line-height: 1.6;
    }
    h1 { color: #2563eb; font-size: 24px; margin-bottom: 4px; }
    .subtitle { color: #666; font-size: 14px; margin-bottom: 24px; }
    .note { white-space: pre-wrap; font-size: 14px; }
    .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e5e7eb; font-size: 12px; color: #999; }
  </style>
</head>
<body>
  <h1>📝 EziNotes</h1>
  <p class="subtitle">NDIS Support Note ${clientName ? `- ${clientName}` : ''}</p>
  <div class="note">${note}</div>
  <div class="footer">Generated by EziNotes • ${new Date().toLocaleDateString('en-AU')}</div>
</body>
</html>`

    const printWindow = window.open('', '_blank')
    if (printWindow) {
      printWindow.document.write(content)
      printWindow.document.close()
      printWindow.print()
    }
  }

  return (
    <button
      onClick={generatePDF}
      disabled={!note}
      style={{
        padding: '8px 16px',
        borderRadius: '8px',
        border: 'none',
        background: note ? '#7c3aed' : '#d1d5db',
        color: 'white',
        fontSize: '13px',
        fontWeight: '500',
        cursor: note ? 'pointer' : 'not-allowed',
        display: 'flex',
        alignItems: 'center',
        gap: '6px',
      }}
    >
      📄 PDF
    </button>
  )
}
