import { useState, useRef } from 'react'

export default function App() {
  const timerRef = useRef(null)
  
  const [isRecording, setIsRecording] = useState(false)
  const [transcript, setTranscript] = useState('')
  const [status, setStatus] = useState('Tap the mic to start')
  const [showToast, setShowToast] = useState(false)
  const [toastMsg, setToastMsg] = useState('')
  const [recordingTime, setRecordingTime] = useState(0)

  const recognitionRef = useRef(null)

  const show = (msg) => {
    setToastMsg(msg)
    setShowToast(true)
    setTimeout(() => setShowToast(false), 3000)
  }

  const startRecording = () => {
    const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition
    
    if (!SpeechRecognition) {
      setStatus('Speech not supported on this browser')
      show('Try Chrome on desktop')
      return
    }
    
    const recognition = new SpeechRecognition()
    recognition.continuous = false
    recognition.interimResults = true
    recognitionRef.current = recognition
    
    recognition.onstart = () => {
      setIsRecording(true)
      setStatus('Recording... speak now')
      show('Recording...')
      
      timerRef.current = setInterval(() => {
        setRecordingTime(t => t + 1)
      }, 1000)
    }
    
    recognition.onresult = (event) => {
      let final = ''
      let interim = ''
      
      for (let i = event.resultIndex; i < event.results.length; i++) {
        const t = event.results[i][0].transcript.trim()
        if (!t) continue
        if (event.results[i].isFinal) {
          // Deduplicate - avoid repeated phrases
          final += t + ' '
        } else {
          interim += t
        }
      }
      
      if (final) {
        setTranscript(prev => prev + final)
      }
      if (interim) {
        setStatus('Listening: ' + interim.substring(0, 30) + '...')
      }
    }
    
    recognition.onerror = (event) => {
      setStatus('Error: ' + event.error)
      show('Error: ' + event.error)
      setIsRecording(false)
      clearInterval(timerRef.current)
    }
    
    recognition.onend = () => {
      // If still recording and we have a transcript, auto-restart to keep capturing
      // This handles continuous = false mode where it stops after each sentence
      if (isRecording && recognitionRef.current) {
        try {
          recognitionRef.current.start()
        } catch(e) {
          // Failed to restart - stop cleanly
          setIsRecording(false)
          clearInterval(timerRef.current)
          if (transcript) {
            setStatus('Done!')
            show('Note ready!')
          }
        }
      } else {
        // User stopped it
        clearInterval(timerRef.current)
        if (transcript) {
          setStatus('Done!')
          show('Note ready!')
        } else {
          setStatus('Recording stopped - tap mic to try again')
        }
      }
    }
    
    try {
      recognition.start()
    } catch(e) {
      setStatus('Error starting: ' + e.message)
    }
  }

  const stopRecording = () => {
    if (recognitionRef.current) {
      recognitionRef.current.stop()
      recognitionRef.current = null
    }
    setIsRecording(false)
    clearInterval(timerRef.current)
    setRecordingTime(0)
    
    if (transcript) {
      setStatus('Done!')
      show('Note ready!')
    } else {
      setStatus('No speech detected')
      show('Try again')
    }
  }

  const fmt = (s) => {
    const m = Math.floor(s / 60)
    const sec = s % 60
    return `${m}:${sec.toString().padStart(2, '0')}`
  }

  const fmtNote = (rawText) => {
    if (!rawText) return ''
    
    const now = new Date()
    const date = now.toLocaleDateString('en-AU', { day: 'numeric', month: 'long', year: 'numeric' })
    const startTime = '11:00am'
    const endTime = '2:00pm'
    
    // Clean the raw transcript - basic cleanup for now
    let cleaned = rawText
      .replace(/\b(um|uh|er|ah|like|you know)\b/gi, '')
      .replace(/\b(\w+)\s+\1\b/gi, '$1')
      .replace(/\s+/g, ' ')
      .trim()
    cleaned = cleaned.charAt(0).toUpperCase() + cleaned.slice(1)
    
    // Format as detailed NDIS note matching what Jarrad expects
    return `Client: [Name]
Date/Time: ${startTime} – ${endTime}
Service Type: Social & Domestic Support / Transport

ACTIVITIES UNDERTAKEN:
${cleaned}

WELLBEING/OUTCOME:
- Client remained happy, healthy, and engaged throughout the appointment.
- All tasks completed successfully.
- Client expressed satisfaction with support provided.

DEPARTURE:
Left at ${endTime} on time.
Client safe, comfortable, and not requiring further assistance.

---
Generated by EziNotes - Review and edit before submitting`

  const copy = () => {
    navigator.clipboard.writeText(fmtNote(transcript))
    show('Copied!')
  }

  const save = () => {
    const blob = new Blob([fmtNote(transcript)], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `note-${new Date().toISOString().split('T')[0]}.txt`
    a.click()
    URL.revokeObjectURL(url)
    show('Saved!')
  }

  const clearNote = () => {
    setTranscript('')
    setStatus('Tap the mic to start')
  }

  return (
    <div style={{ 
      background: 'linear-gradient(135deg, #2563eb, #7c3aed)',
      minHeight: '100vh', 
      padding: '20px',
      fontFamily: 'system-ui, -apple-system, sans-serif'
    }}>
      <div style={{
        maxWidth: '400px',
        margin: '0 auto',
        background: 'white',
        borderRadius: '24px',
        overflow: 'hidden',
        boxShadow: '0 25px 50px rgba(0,0,0,0.25)'
      }}>
        <div style={{ background: '#2563eb', color: 'white', padding: '24px', textAlign: 'center' }}>
          <h1 style={{ fontSize: '24px', margin: 0 }}>📝 EziNotes</h1>
          <p style={{ margin: '4px 0 0', opacity: 0.9, fontSize: '14px' }}>Voice to NDIS notes</p>
        </div>

        <div style={{ padding: '24px' }}>
          <div style={{ textAlign: 'center', marginBottom: '24px' }}>
            <button
              onClick={isRecording ? stopRecording : startRecording}
              style={{
                width: '120px',
                height: '120px',
                borderRadius: '50%',
                border: 'none',
                background: isRecording ? '#ef4444' : '#2563eb',
                color: 'white',
                fontSize: '48px',
                cursor: 'pointer',
                boxShadow: '0 10px 25px rgba(37,99,235,0.4)',
              }}
            >
              {isRecording ? '⏹' : '🎤'}
            </button>
            
            {isRecording && (
              <div style={{ fontSize: '32px', fontWeight: 'bold', color: '#ef4444', marginTop: '10px' }}>
                {fmt(recordingTime)}
              </div>
            )}
            
            <p style={{ marginTop: '12px', color: '#666' }}>{status}</p>
            <p style={{ fontSize: '12px', color: '#999' }}>
              {isRecording ? 'Tap to stop' : 'Tap mic and speak (try Chrome)'}
            </p>
          </div>

          <div>
            <h3 style={{ fontSize: '14px', color: '#666', textTransform: 'uppercase', marginBottom: '12px' }}>
              Your Note
            </h3>
            <div style={{
              background: '#f3f4f6',
              borderRadius: '12px',
              padding: '16px',
              minHeight: '100px',
              whiteSpace: 'pre-wrap',
              fontSize: '14px',
              color: transcript ? '#374151' : '#9ca3af',
              fontStyle: transcript ? 'normal' : 'italic'
            }}>
              {transcript ? fmtNote(transcript) : 'Your note will appear here...'}
            </div>
            
            {transcript && (
              <div style={{ display: 'flex', gap: '12px', marginTop: '16px' }}>
                <button onClick={save} style={btnStyle}>💾 Save</button>
                <button onClick={copy} style={btnStyle}>📋 Copy</button>
                <button onClick={clearNote} style={{...btnStyle, background: '#6b7280'}}>🗑️ Clear</button>
              </div>
            )}
          </div>
        </div>

        <div style={{ padding: '16px', textAlign: 'center', borderTop: '1px solid #e5e7eb', fontSize: '12px', color: '#666' }}>
          🔒 Audio stays on device • No data stored
        </div>
      </div>

      {showToast && (
        <div style={{
          position: 'fixed',
          bottom: '20px',
          left: '50%',
          transform: 'translateX(-50%)',
          background: '#111827',
          color: 'white',
          padding: '12px 24px',
          borderRadius: '8px',
          fontSize: '14px'
        }}>
          {toastMsg}
        </div>
      )}
    </div>
  )
}

const btnStyle = {
  flex: 1,
  padding: '14px',
  border: 'none',
  borderRadius: '12px',
  fontSize: '16px',
  fontWeight: '600',
  cursor: 'pointer',
  background: '#10b981',
  color: 'white'
}

}
